---
title: "Lab 04 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Conor Lacey"
date: "02-07-23"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
suppressWarnings(library(tidyverse))
library(dsbox) 
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
dn <- dennys
lq <- laquinta
```

### Exercise 1

```{r Dennys-Alaska}
dn_ak <- dn %>%
  filter(state == "AK")
nrow(dn_ak)
```

Wow. There are only 3 Denny's locations in Alasksa.

### Exercise 2

```{r La_Quinta-Alaska}
lq_ak <- lq %>%
  filter(state == "AK")
nrow(lq_ak)
```

Alaska is not very popular. There are only 2 La Quintas in Alaska.

### Exercise 3

Now we need to join all Denny's locations with all La Quinta locations in Alaska. From the looks of things we will need to calculate 6 distances. 
```{r join-lq_ak-dn_ak}
dn_lq_ak <- full_join(dn_ak, lq_ak, by = "state")
dn_lq_ak
```

### Exercise 4

...

### Exercise 5

...

### Exercise 6

...

Add exercise headings as needed.
